<% header(name + ' ' + versionString + ' Release Notes') %>

<p><% name %> version <% versionString %> released on <% releaseDate %></p>

<a name="Introduction"></a><h2>Introduction</h2>
<ul>
	<li>...</li>
</ul>

<a name="MajorChanges"></a><h2>Major Changes</h2>
<ul>
	<li>...</li>
</ul>

<a name="NewFeatures"></a><h2>New Features</h2>
<ul>
	<li>...</li>
</ul>

<a name="Improvements"></a><h2>Improvements and Refinements</h2>
<ul>
	<li>...</li>
</ul>

<a name="Security"></a><h2>Security</h2>
<ul>
	<li>If the KidKit Plugin cannot be installed (e.g. if Kid is not available),
	then the <span class="filename">.kid</span> extension will be disabled for
	delivery. Otherwise, Kid templates containing passwords or other sensitive
	information would be delivered unparsed to the client in this case.</li>
</ul>

<a name="MinorChanges"></a><h2>Minor API Changes</h2>
<ul>
	<li>...</li>
</ul>

<a name="Bugfixes"></a><h2>Bugfixes</h2>
<ul>
	<li>The output method could only be changed for every template individually.
	Changing the default output method by setting <code>KidOutputMethod</code>
	in <span class="filename">Application.config</span> now works as well.
	(Reported by Frank Barknecht.)</li>
</ul>

<% footer() %>