<% header(name + ' ' + versionString + ' Release Notes') %>

<p><% name %> version <% versionString %> released on <% releaseDate %></p>

<a name="Introduction"></a><h2>Introduction</h2>
<ul>
	<li>...</li>
</ul>

<a name="MajorChanges"></a><h2>Major Changes</h2>
<ul>
	<li>...</li>
</ul>

<a name="NewFeatures"></a><h2>New Features</h2>
<ul>
	<li>The file extensions of the files that shall be parsed as Kid templates
	can now be configured using the setting <code>ExtensionsForKid</code>.
	By default (as before), only files with the extension <code>.kid</code>
	are regarded as Kid templates.</li>
</ul>

<a name="Improvements"></a><h2>Improvements and Refinements</h2>
<ul>
	<li>...</li>
</ul>

<a name="Security"></a><h2>Security</h2>
<ul>
	<li>...</li>
</ul>

<a name="MinorChanges"></a><h2>Minor API Changes</h2>
<ul>
	<li>...</li>
</ul>

<a name="Bugfixes"></a><h2>Bugfixes</h2>
<ul>
	<li>...</li>
</ul>

<% footer() %>