<% header(name + " User's Guide") %>

<p><% name %> version <% versionString %></p>

<p>Created by: <a href="http://stratolab.com">Winston Wolff</a> January 2005</p>

<h2>Synopsis</h2>

<p>KidKit is a Webware plugin to which makes Webware understand *.kid files.
By installing this kit, you can write .kid template files and Webware will render them
automatically without you needing to compile them.</p>

<p>It is in <em>alpha</em> state I would say at the moment (January 2005).
I put it together and it works for some quick tests.
You can access the httmp GET/PUT field variables, and it does &quot;for&quot; loops.
If you use Kid a lot, feel free to improve this component.</p>

<h2>Requirements</h2>

<p>Kid, Element-Tree and Webware.</p>

<p>This was built and tested in January 2005, with Kid v0.4.1 and Element Tree 1.2.4-20041228. Other versions may work.</p>
<ul>
	<li><a href="http://kid-template.sourceforge.net">Kid</a> by Ryan Tomayko</li>
	<li><a href="http://effbot.org/zone/element.htm">Element-Tree</a> by Fredrik Lundh</li>
	<li><a href="http://www.webwareforpython.org">Webware</a> CVS version from January 2005</li>
</ul>

<% footer() %>