#!/bin/sh
#
# Startup script for WebKit
# on UNIX systems.
#
# See Webware/WebKit/Docs/InstallGuide.html for instructions.

# chkconfig: 2345 75 25
# description: WebKit is Python application server, part of Webware.

# Source function library.
. /etc/rc.d/init.d/functions

WEBKIT_DIR=/opt/Webware/WebKit
PID_FILE=/var/run/webkit.pid
LOG=/var/log/webkit
PYTHONPATH=
PYTHONPATH_ADDONS=


[ -f $WEBKIT_DIR/AppServer ] || exit 0

case "$1" in
	start)
		echo -n  "Starting WebKit: "
		pushd $WEBKIT_DIR > /dev/null
		PYTHONPATH="$PYTHONPATH:$PYTHONPATH_ADDONS" ./AppServer >> $LOG 2>&1 &
		echo $! > $PID_FILE
		popd > /dev/null
		success "Starting WebKit"
		echo
		;;

	stop)
		echo -n "Shutting down WebKit: "
		kill -s 2 `cat $PID_FILE`
		success "Shutting down WebKit"
		echo
		;;

	restart)
		$0 stop
		$0 start
		;;

	*)
		echo "Usage: webkit {start|stop|restart}"
		exit 1

esac

exit 0
