<% header(name + ' ' + versionString + ' Release Notes') %>

<p><% name %> version <% versionString %> released on <% releaseDate %></p>

<a name="Introduction"></a><h2>Introduction</h2>
<ul>
	<li>...</li>
</ul>

<a name="MajorChanges"></a><h2>Major Changes</h2>
<ul>
	<li>...</li>
</ul>

<a name="NewFeatures"></a><h2>New Features</h2>
<ul>
	<li>...</li>
</ul>

<a name="Improvements"></a><h2>Improvements and Refinements</h2>
<ul>
	<li>The Scheduler now accepts an <code>exceptionHandler</code> argument.
	If passed, this exception handler is invoked whenever an unhandled exception
	occurs within a <code>Task</code>. Previously there was no general mechanism
	for handling exceptions within Tasks.</li>
	<li>If an exception occurs within a periodic Task, the Task will be started
	again at the next scheduled time. Previously when an exception occurred,
	the Task was not be able to be restarted.</li>
</ul>

<a name="Security"></a><h2>Security</h2>
<ul>
	<li>...</li>
</ul>

<a name="MinorChanges"></a><h2>Minor API Changes</h2>
<ul>
	<li>...</li>
</ul>

<a name="Bugfixes"></a><h2>Bugfixes</h2>
<ul>
	<li>...</li>
</ul>

<% footer() %>
