<% header(name + ' ' + versionString + ' Release Notes') %>

<p><% name %> version <% versionString %> released on <% releaseDate %></p>

<a name="Improvements"></a><h2>Improvements and Refinements</h2>
<ul>
	<li>The Scheduler now accepts an <code>exceptionHandler</code> argument.
	If passed, this exception handler is invoked whenever an unhandled exception
	occurs within a <code>Task</code>. Previously there was no general mechanism
	for handling exceptions within Tasks.</li>
	<li>If an exception occurs within a periodic Task, the Task will be started
	again at the next scheduled time. Previously when an exception occurred,
	the Task was not be able to be restarted.</li>
</ul>

<% footer() %>
