<% header(name + ' ' + versionString + ' Release Notes') %>

<p><% name %> version <% versionString %> released on <% releaseDate %></p>

<a name="Introduction"></a><h2>Introduction</h2>
<ul>
	<li>...</li>
</ul>

<a name="MajorChanges"></a><h2>Major Changes</h2>
<ul>
	<li>...</li>
</ul>

<a name="NewFeatures"></a><h2>New Features</h2>
<ul>
	<li>...</li>
</ul>

<a name="Improvements"></a><h2>Improvements and Refinements</h2>
<ul>
	<li>Config files are now opened in universal newline mode. This means
	you can now edit config files for Webware running under one platform
	(e.g. Unix) with an editor running on a different platform (e.g. Windows)
	without causing any troubles.</li>
</ul>

<a name="Security"></a><h2>Security</h2>
<ul>
	<li>...</li>
</ul>

<a name="MinorChanges"></a><h2>Minor API Changes</h2>
<ul>
	<li>...</li>
</ul>

<a name="Bugfixes"></a><h2>Bugfixes</h2>
<ul>
	<li>...</li>
</ul>

<% footer() %>