<% header(name + ' ' + versionString + ' Release Notes') %>

<p><% name %> version <% versionString %> released on <% releaseDate %></p>

<a name="Improvements"></a><h2>Improvements and Refinements</h2>
<ul>
	<li>Config files are now opened in universal newline mode. This means you
	can now edit config files for Webware running under one platform (e.g. Unix)
	with an editor running on a different platform (e.g. Windows) without
	causing any troubles.</li>
</ul>

<% footer() %>