<% header(name + ' ' + versionString + ' Release Notes') %>

<p><% name %> version <% versionString %> released on <% releaseDate %></p>

<a name="Introduction"></a><h2>Introduction</h2>
<ul>
	<li>...</li>
</ul>

<a name="MajorChanges"></a><h2>Major Changes</h2>
<ul>
	<li>...</li>
</ul>

<a name="NewFeatures"></a><h2>New Features</h2>
<ul>
	<li>You can now use an arbitrary encoding for your PSP files if you
	specify the encoding in the <code>PSPFileEncoding</code> setting.</li>
</ul>

<a name="Improvements"></a><h2>Improvements and Refinements</h2>
<ul>
	<li>...</li>
</ul>

<a name="Security"></a><h2>Security</h2>
<ul>
	<li>...</li>
</ul>

<a name="MinorChanges"></a><h2>Minor API Changes</h2>
<ul>
	<li>...</li>
</ul>

<a name="Bugfixes"></a><h2>Bugfixes</h2>
<ul>
	<li>When using the psp-handler of mod_webkit, request methods like
	<code>servletPath()</code> and others returned values which were different
	from what you get when using the ordinary webkit-handler. This could
	cause various problems, for instance because the default cookie path
	is set to the servlet path (reported by Fionn Behrens). To avoid such
	problems, requests made via the psp-handler now will look much more
	similar to a request made via the ordinary webkit-handler.</li>
</ul>

<% footer() %>