<% header(name + ' ' + versionString + ' Release Notes') %>

<p><% name %> version <% versionString %> released on <% releaseDate %></p>

<a name="Introduction"></a><h2>Introduction</h2>
<ul>
	<li>...</li>
</ul>

<a name="MajorChanges"></a><h2>Major Changes</h2>
<ul>
	<li>...</li>
</ul>

<a name="NewFeatures"></a><h2>New Features</h2>
<ul>
	<li>Added new methods <code>writeMetaData()</code> and
	<code>writeJavaScript()</code> to the <code>Page</code> class
	that will be called by <code>writeHeadParts()</code>.</li>
	<li>The Examples context has now a servlet <code>AjaxSuggest</code>
	demonstrating the use of Ajax with Webware for Python.
	A baseclass <code>AjaxPage</code> and the necessary JavaScript
	supporting these techniques are also included in the Examples context.</li>
</ul>

<a name="Improvements"></a><h2>Improvements and Refinements</h2>
<ul>
	<li>...</li>
</ul>

<a name="Security"></a><h2>Security</h2>
<ul>
	<li>...</li>
</ul>

<a name="MinorChanges"></a><h2>Minor API Changes</h2>
<ul>
	<li>...</li>
</ul>

<a name="Bugfixes"></a><h2>Bugfixes</h2>
<ul>
	<li>...</li>
</ul>

<% footer() %>