<% header(name + ' ' + versionString + ' Release Notes') %>

<p><% name %> version <% versionString %> released on <% releaseDate %></p>

<a name="Introduction"></a><h2>Introduction</h2>
<ul>
	<li>...</li>
</ul>

<a name="MajorChanges"></a><h2>Major Changes</h2>
<ul>
	<li>...</li>
</ul>

<a name="NewFeatures"></a><h2>New Features</h2>
<ul>
	<li>Added new methods <code>writeMetaData()</code> and
	<code>writeJavaScript()</code> to the <code>Page</code> class
	that will be called by <code>writeHeadParts()</code>.</li>
	<li>The Examples context has now a servlet <code>AjaxSuggest</code>
	demonstrating the use of Ajax with Webware for Python.
	A baseclass <code>AjaxPage</code> and the necessary JavaScript
	supporting these techniques are also included in the Examples context.</li>
</ul>

<a name="Improvements"></a><h2>Improvements and Refinements</h2>
<ul>
	<li>The auto reloading app server used the <code>ImportSpy</code> module
	to keep track of which modules have been imported. <code>ImportSpy</code>
	was based on the old <code>ihooks</code> module which could raise problems
	with other incompatible importing mechanisms like Cheetah templates or
	when using zipped Python eggs. This problem has been tackled from two sides,
	first by replacing ihooks with new (PEP 302) import hooks if available
	(they were implemented in Python 2.3), and second by allowing to suppress
	the use of <code>ImportSpy</code> completely by setting
	<code>UseImportSpy</code> to False in <code>Application.config</code>.
	In this case, <code>sys.modules</code> will be polled regularly.
	The <code>ImportSpy</code> module now contains only the import hooks,
	the rest of the functionality for tracking and managing concurrent import
	has been sourced out to the new <code>ImportManager</code> module.</li>
	<li>The start script for RedHat/Fedora Linux has been improved. A timing issue
	with the "restart" option has been solved.</li>
</ul>

<a name="Security"></a><h2>Security</h2>
<ul>
	<li>...</li>
</ul>

<a name="MinorChanges"></a><h2>Minor API Changes</h2>
<ul>
	<li>...</li>
</ul>

<a name="Bugfixes"></a><h2>Bugfixes</h2>
<ul>
	<li>Fixed bug in HTTP server that prevented multiple cookies from being
	set at the same time.</li>
</ul>

<% footer() %>