<% header(name + ' ' + versionString + ' Release Notes') %>

<p><% name %> version <% versionString %> released on <% releaseDate %></p>

<a name="Introduction"></a><h2>Introduction</h2>
<ul>
	<li>...</li>
</ul>

<a name="MajorChanges"></a><h2>Major Changes</h2>
<ul>
	<li>...</li>
</ul>

<a name="NewFeatures"></a><h2>New Features</h2>
<ul>
	<li>...</li>
</ul>

<a name="Improvements"></a><h2>Improvements and Refinements</h2>
<ul>
	<li><code>urlDecode()</code> and <code>urlEncode()</code> in
	<code>WebUtils.Funcs</code> now use the same implementation as
	<code>quote_plus()</code> and <code>unquote_plus()</code> in
	<code>urllib</code> of Python 2.4, which is faster than in older
	Python and Webware versions. This also means that <code>urlDecode()</code>
	now silently ignores erroneous encoding (as had been suggested
	by Ben Parker), including codes with only one digit.</li>
</ul>

<a name="Security"></a><h2>Security</h2>
<ul>
	<li>...</li>
</ul>

<a name="MinorChanges"></a><h2>Minor API Changes</h2>
<ul>
	<li>...</li>
</ul>

<a name="Bugfixes"></a><h2>Bugfixes</h2>
<ul>
	<li>...</li>
</ul>

<% footer() %>