<% header(name + ' ' + versionString + ' Release Notes') %>

<p><% name %> version <% versionString %> released on <% releaseDate %></p>

<a name="Introduction"></a><h2>Introduction</h2>
<ul>
	<li>...</li>
</ul>

<a name="MajorChanges"></a><h2>Major Changes</h2>
<ul>
	<li>...</li>
</ul>

<a name="NewFeatures"></a><h2>New Features</h2>
<ul>
	<li>...</li>
</ul>

<a name="Improvements"></a><h2>Improvements and Refinements</h2>
<ul>
	<li>Made urlDecode() behave like urllib.unquote_plus():
    All illegal codes will now be silently ignored (suggested
    by Ben Parker). Like implemented in Python 2.4, codes with only
    one digit will be considered illegal now.</li>
    <li>Instead of urlEncode() and urlDecode(), you should use
    urllib.quote_plus() and urllib.unquote_plus() from Python 2.4 on,
    since this is implemented now faster in urllib, and the behavior is
    now the same. Added a note to the docstrings of these functions.</li>
</ul>

<a name="Security"></a><h2>Security</h2>
<ul>
	<li>...</li>
</ul>

<a name="MinorChanges"></a><h2>Minor API Changes</h2>
<ul>
	<li>...</li>
</ul>

<a name="Bugfixes"></a><h2>Bugfixes</h2>
<ul>
	<li>...</li>
</ul>

<% footer() %>