<% header(name + ' ' + versionString + ' Release Notes') %>

<p><% name %> version <% versionString %> released on <% releaseDate %></p>

<a name="Introduction"></a><h2>Introduction</h2>
<ul>
  <li>...</li>
</ul>

<a name="MajorChanges"></a><h2>Major Changes</h2>
<ul>
  <li>...</li>
</ul>

<a name="NewFeatures"></a><h2>New Features</h2>
<ul>
  <li>...</li>
</ul>

<a name="Improvements"></a><h2>Improvements and Refinements</h2>
<ul>
  <li>...</li>
</ul>

<a name="Security"></a><h2>Security</h2>
<ul>
  <li>...</li>
</ul>

<a name="MinorChanges"></a><h2>Minor API Changes</h2>
<ul>
  <li>To conform with Webwares naming conventions and because it now deviates
  pretty much from the original <code>cgitb</code>, renamed
  <code>WebUtils.cgitb</code> to <code>WebUtils.CGITraceback</code>.</li>
</ul>

<a name="Bugfixes"></a><h2>Bugfixes</h2>
<ul>
  <li>...</li>
</ul>

<a name="Deprecations"></a><h2>Deprecations</h2>
<ul>
  <li>The methods and objects which have been marked as deprecated
  in version 1.0 and modules that are now available in the standard library
  have been removed in Webware for Python 1.1, particularly
  <code>Cookie</code>, <code>cgitb</code> and <code>WebFuncs</code>.</li>
</ul>

<% footer() %>
