<% header(name + ' ' + versionString + ' Release Notes') %>

<p><% name %> version <% versionString %> released on <% releaseDate %></p>

<ul>
	<li>This release of Webware for Python includes a couple of fixes and
	improvements of WebKit, MiddleKit, MiscUtils and WebUtils (see
	the respective release notes).</li>
	<li>An interesting new feature is the possibility to dump stack frames
	of all running threads to standard output by sending a SIGQUIT or SIGBREAK
	signal to the Application server.</li>
	<li>The current version should run with all Python versions from
	2.0 to 2.5 (KidKit requires version 2.3). This will probably be the last
    Webware release to support Python versions before 2.3.</li>
</ul>

<% footer() %>