<% header(name + ' ' + versionString + ' Release Notes') %>

<p><% name %> version <% versionString %> released on <% releaseDate %></p>

<ul>
	<li>This is the first beta release of Webware for Python 1.0.
	We consider this the final and long-time stable version of the
	original framework that will stay compatible with all Python 2.x
	versions. Bug-fix releases will be called 1.0.x.
	See also the release notes of WebKit, TaskKit and CGIWrapper
	for some improvements made in these components.</li>
</ul>

<% footer() %>